name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Tests (Django)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install django-environ

      - name: Lint (opcional)
        run: |
          echo "Skipping lint for now"
          # pip install flake8
          # flake8 .

      - name: Run Django checks
        env:
          # Config mínima para checks sin DB productiva
          DJANGO_SETTINGS_MODULE: tienda_gongora.settings
        run: |
          python - <<'PY'
          import os
          os.environ.setdefault("DJANGO_SETTINGS_MODULE","tienda_gongora.settings")
          from django.core.management import call_command
          call_command("check")
          PY

      # (Opcional) Añade tus tests cuando estén listos
      # - name: Run tests
      #   run: python manage.py test

  deploy:
    name: Deploy to VPS
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Rsync code to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT || 22 }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH || '/srv/gongorajoyeria/app' }}
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "venv" \
            --exclude ".env" \
            --exclude "staticfiles" \
            --exclude "media" \
            --exclude "node_modules" \
            -e "ssh -p $SSH_PORT -i ~/.ssh/id_ed25519" \
            ./ "${SSH_USER}@${SSH_HOST}:${REMOTE_PATH}/"

      - name: Run deploy script (migrate, collectstatic, restart)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT || 22 }}
          REMOTE_SCRIPT: ${{ secrets.REMOTE_SCRIPT || '/srv/gongorajoyeria/deploy/deploy.sh' }}
        run: |
          ssh -p "$SSH_PORT" -i ~/.ssh/id_ed25519 "${SSH_USER}@${SSH_HOST}" "bash '$REMOTE_SCRIPT'"
